### ISSUE TITLE
outdated signing method

### ISSUE THREAD

**Issue by kenny019** [SleepWalker/tuya-cloud-api#31]
due to tuya updating their api signature algorithim, the old signing method is outdated

you will get sign invalid (1004) when trying to request token or any request.

- https://developer.tuya.com/en/docs/iot/new-singnature?id=Kbw0q34cs2e5g#title-5-Headers

**Comment by SleepWalker** [comment]
hello. Sorry for the late reply.

Actually I'm using the lib on everyday basis and there is no issues with signatures :thinking: I will read new docs and review you PR

BTW. I've found that there is official SDK https://github.com/tuya/tuya-connector-Nodejs. So probably this repository should be archived instead of updated (This is only assumption because I haven't read the docs/source of that SDK yet)

**Comment by kenny019** [comment]
hi, not sure about signature issue. might it be that because i am using the eu server?

i was not aware of the tuya-connector library will have to look into it. but currently this library is working fine with the updated signature method for my use case!

**Comment by SleepWalker** [comment]
released in https://github.com/SleepWalker/tuya-cloud-api/releases/tag/v1.2.0
